namespace SpriteKind {
    export const PowerUP = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(assets.image`myImage8`, mySprite, 200, 0)
    music.play(music.melodyPlayable(music.pewPew), music.PlaybackMode.UntilDone)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite2, otherSprite2) {
    scene.cameraShake(8, 500)
    info.changeLifeBy(-1)
    enemyDeath(otherSprite2)
    music.play(music.melodyPlayable(music.powerDown), music.PlaybackMode.UntilDone)
})
statusbars.onZero(StatusBarKind.EnemyHealth, function (status) {
    music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
    enemyDeath(status.spriteAttachedTo())
})
function enemyDeath (enemy: Sprite) {
    sprites.destroy(enemy, effects.disintegrate, 500)
}
info.onLifeZero(function () {
    carnival.customGameOverExpanded("You Died")
    carnival.onGameOverExpanded(carnival.WinTypes.Score)
    web.open("http://192.168.111.210:889/api/ECommReflection?playername=" + info.score() + "&score=" + info.score())
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, otherSprite).value += -30
    info.changeScoreBy(1)
    sprites.destroy(sprite, effects.disintegrate, 500)
})
let statusbar: StatusBarSprite = null
let enemyShip: Sprite = null
let projectile: Sprite = null
let mySprite: Sprite = null
effects.starField.startScreenEffect()
mySprite = sprites.create(assets.image`myImage6`, SpriteKind.Player)
controller.moveSprite(mySprite)
mySprite.setStayInScreen(true)
info.setScore(0)
info.setLife(5)
scroller.scrollBackgroundWithSpeed(-90, 0)
game.onUpdateInterval(2000, function () {
    enemyShip = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........99.....5......
        .........9999...55......
        ......22229922222.......
        ........222255522.......
        ............555.........
        .............55.........
        ..............5.........
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    enemyShip.x = scene.screenWidth()
    enemyShip.vx = -90
    enemyShip.y = randint(10, scene.screenHeight() - 10)
    statusbar = statusbars.create(15, 2, StatusBarKind.EnemyHealth)
    statusbar.attachToSprite(enemyShip)
})
